### ISSUE TITLE
Oneko strange layering issue

### ISSUE THREAD

**Issue by JonDoeBeep** [flathub/com.daidouji.oneko#8]
When running on aarch64 fedora, oneko's images seem to layer.
Steps to replicate:
Download oneko flatpak
Run it

![Screenshot_20231109_133030](https://github.com/flathub/com.daidouji.oneko/assets/56412184/1a56e439-4ea1-402b-bcd8-e163a3379be7)

**Comment by jcleng** [comment]
maybe you used wayland, only x11

**Comment by NeuHix** [comment]
Any plans to support wayland ?
On wayland, Oneko only follows my cursor when I click & drag oneko somewhere.

**Comment by jcleng** [comment]
no, i just package for flatpak, source code is so long time not to update
